config/routes.rb
Rails.application.routes.draw do
  
  namespace :api do 
    resources :users do 
      resources :books do 
        resources :contacts 
      end 
    end
  end 
  
  get    "login"  => "sessions#new"
  post   "login"  => "sessions#create"
  get    "logout" => "sessions#destroy"
  resources :sessions 
  
  
  root "sessions#index"
  
  get "signup" => "users#new"
  resources :users do 
    resources :books do 
      resources :contacts 
    end 
  end 
  
  
    

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :books
  has_many :contacts 
  #add test 
  before_save { self.email = email.downcase } 
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :first_name, presence: true, length: { maximum: 50 }
  validates :email,      presence: true, length: { maximum: 255 },
                         format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  has_secure_password 
end

app/controllers/api/users_controller.rb
class Api::UsersController< Api::ApiController  
  
  def show 
    @user = User.find(params[:id])
    render json: @user 
  end 
  
  def create 
    @user = User.new(user_params)
    if @user.save 
      render status: 200, json: { message: "You have successfully registered", user: @user }.to_json 
    else 
      render status: 422, json: { message: "There is an error with your form", user: @user }.to_json
    end
  end 
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    render status: 200, json: { message: "User has been deleted" }.to_json
  end 
  
  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_digest) 
    end 
  
  
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_action :require_user, except: [:new, :cr

 def show 
    @user = User.find(session[:user_id])
 end 
  
  def new
    @user = User.new 
  end
  
  def create 
    @user = User.new(user_params)
    if @user.save 
      flash[:success] = "You have successfully registered"
      session[:user_id] = @user.id
      redirect_to user_path(session[:user_id]) 
    else 
      flash[:error] = "There is an error with your form"
      render :new 
    end
  end 
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy 
    flash[:success] = "User has been deleted"
    redirect_to users_path
  end 
  
  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_digest) 
    end 
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<h1> Sign Up</h1>


<div class="container">
  <%= form_for @user do |f| %>
    <p> 
      <%= f.label :first_name %>
    </p>
    <p>
      <%= f.text_field :first_name %> 
    </p>
    <p>
      <%= f.label :last_name %>
    </p>
    <p>
      <%= f.text_field :last_name %> 
    </p>
    <p>
      <%= f.label :email %>
    </p>
    <p>
      <%= f.text_field :email  %> 
    </p>
    <p>
      <%= f.label :password %>
    </p>
    <p>
      <%= f.password_field :password %>
    </p>
    <p>
      <%= f.label :password_confirmation %>
    </p>
    <p>
      <%= f.password_field :password_confirmation %>  
    </p>
    <p>
      <%= f.submit :Register, class: "btn btn-success" %>
    </p>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <h1> Welcome to Your Profile <%= @user.first_name.capitalize %> </h1>
  <hr/>
</div>

<div class="container">
  <%= link_to "Add New Address Book", new_user_book_path(session[:user_id]) %>
</div>

<div class="container">
  <h3> Address Books: </h3>
</div>


<div class="container">
  <table class="table table-striped">
    <% @user.books.each do |book| %>
      <tr>
        <td> 
          <strong> <%= book.name.capitalize %> </strong> 
        </td>
         
        <td>
           <%= link_to "show", user_book_path(@user.id, book.id) %> 
        </td>
        <td>
          <%= link_to "delete", 
                            user_book_path(@user.id, book.id), method: :delete, data: { confirm: "Are you sure?" } %>
        </td>
      </tr>
    <% end %>
  </table>
</div>