config/routes.rb
Rails.application.routes.draw do
  
  namespace :api do 
    resources :users do 
      resources :books do 
        resources :contacts 
      end 
    end
  end 
  
  get    "login"  => "sessions#new"
  post   "login"  => "sessions#create"
  get    "logout" => "sessions#destroy"
  resources :sessions 
  
  
  root "sessions#index"
  
  get "signup" => "users#new"
  resources :users do 
    resources :books do 
      resources :contacts 
    end 
  end 
  
  
    

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
  has_many :contacts 
  
  validates :name, presence: true, length: { within: 3..155 }
  validates :user_id, presence: true 
end

app/controllers/api/books_controller.rb
class Api::BooksController < Api::ApiController 
  
  def show 
    @user = User.find(current_user)
    @book = @user.books.find(params[:id])
    render json: { 
      user: @user, 
      book: @book 
    }.json 
  end 
  
  def create
    @user = User.find(current_user)
    @book = @user.books.build(book_params)
    if @book.save 
      render status: 200, json: { 
        message: "Address book '#{book.name}'' has been created successfully", 
        user: @user, 
        book: @book 
      }.to_json
    else 
      render status: 422, json: { 
        message: "Error creating the book", 
        user: @user, 
        book: @book 
      }.to_json
    end
  end 
  
  def destroy
    @user = User.find(current_user)
    @book = @user.books.find(params[:id])
    @book.destroy 
    render status: 200, json: { 
      message: "Address book succesfully destroyed", 
      user: @user, 
      book: @book 
    }.to_json
  end 
  
  private 
    def book_params 
      params.require(:book).permit(:name)
    end 
  
end 

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :require_user

  
  def show 
    @user = User.find(session[:user_id])
    @book = @user.books.find(params[:id])
  end 

  def new
    @user = User.find(session[:user_id])
    @book = Book.new 
  end
  
  
  def create
    @user = User.find(session[:user_id])
    @book = @user.books.build(book_params)
    if @book.save 
      flash[:success] = "Address book '#{@book.name}'' has been created successfully"
      redirect_to user_path(@user)
    else 
      flash.now[:error] = "Error creating the book"
      render :new 
    end
  end 
  
  def destroy
    @user = User.find(params[:user_id])
    @book = @user.books.find(params[:id])
    flash[:success] = "Address book succesfully destroyed"
    @book.destroy 
    redirect_to user_path(@user)
  end 
  
  private 
    def book_params 
      params.require(:book).permit(:name)
    end 
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/index.html.erb
<% @books.each do |book| %>
  <p>
    <%= book.name %> | <%= link_to "Add Contact", new_user_book_contact_path(book.user_id, book.id) %>
  </p>
  
     <% book.contacts.each do |contact| %>
      <ul>
        <li> <%= contact.first_name.capitalize %> | <%= contact.address %> | < </li>
      </ul>
    <% end %>
  </p>
  

<% end %> 

app/views/books/new.html.erb
<div class="container">
  <h1> New Address Book </h1>
</div>


<div class="container">
  <%= form_for [@user, @book] do |f| %>
    <p>
      <%= f.label :name %> 
    </p>
    <p>
      <%= f.text_field :name %> 
    </p>
    <p>
      <%= f.submit "Create", class: "btn btn-success" %> 
    </p>
  <% end %>
</div>

app/views/books/show.html.erb
<h1> <%= @book.name.capitalize %> </h1>

<div class="container">
  <h4> <%= link_to "Add new contact", new_user_book_contact_path(@user, @book) %> </h4>
</div>

<div class="container">
  <h3> Contacts: </h3>
</div>

<div class="container">
  <% if @book.contacts.empty? %>
    <p> You have no contacts. <%= link_to "Add your first one!", new_user_book_contact_path(@user, @book) %> </p>
  <% else %>
    <table class="table table-striped">
      <thead>
        <tr>
          <td>
            <strong> First name </strong>
          </td>
          <td>
            <strong> Last name </strong>
          </td>
          <td>
            <strong> Address </strong>
          </td>
          <td>
            <strong> Action </strong>
          </td>
        </tr>
      </thead>
      <% @book.contacts.each do |contact| %>
      <tr>
        <td>
          <%= contact.first_name.capitalize %>
        </td>
        <td>
          <%= contact.last_name.capitalize %>
        </td>
        <td>
          <%= contact.address %> 
        </td>
        <td>
          <%= link_to "delete", user_book_contact_path(@user, @book, contact.id), method: :delete,
                      data: { confirm: "Are you sure?" } %> 
          </td>
        </tr>
        <% end %>
      </table>
  <% end %>
  <%= link_to "Back", user_path(@user) %>
</div>