config/routes.rb
Rails.application.routes.draw do
  
  namespace :api do 
    resources :users do 
      resources :books do 
        resources :contacts 
      end 
    end
  end 
  
  get    "login"  => "sessions#new"
  post   "login"  => "sessions#create"
  get    "logout" => "sessions#destroy"
  resources :sessions 
  
  
  root "sessions#index"
  
  get "signup" => "users#new"
  resources :users do 
    resources :books do 
      resources :contacts 
    end 
  end 
  
  
    

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AddressBook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Address Book", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Home", root_path %> </li>
            <% if logged_in? %>
              <li><%= link_to "Logout", logout_path %></li>
            <% else %>
              <li> <%= link_to "Login", login_path %> </li>
            <% end %> 
          </ul>
        </nav>
      </div>
    </header>
    <body>
      <div class="container">
        <% flash.each do |type, message| %>
          <div class="alert alert-<%= type %>">
              <%= message %>
            <% end %> 
          </div>
        <%= yield %>
      </div> 
  </body>
</html>